name: insta
description: A new Flutter project.

# publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.6.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  path_provider: ^2.1.1
  font_awesome_flutter: ^10.5.0
  fluttertoast: ^8.2.2
  http: ^1.1.0
  flutter_local_notifications: ^17.2.2
  dio: ^5.4.0
  permission_handler: ^11.0.1
  webview_flutter: ^4.4.4
  encrypt: ^5.0.0
  url_launcher: ^6.2.4
  adaptive_theme: ^2.3.1
  device_info_plus: ^10.0.0
  video_thumbnail: ^0.5.3
  speed_dial_fab: ^2.2.1
  chewie: ^1.3.4
  video_player: ^2.4.6
  story_view: ^0.16.5
  image_picker: ^1.1.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - .env
  uses-material-design: true
