name: Flutter Test

on:
  push:
    branches: ["main"]

jobs:
  analyze:
    name: Analyze Dart Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - name: Flutter analyze
        run: flutter analyze --no-fatal-infos

